### ISSUE TITLE
final build error

### ISSUE THREAD

**Issue by Rainerr123** [Devilx86/ImpostorModmenu#35]
i get a corrupt file error when trying to install after building and injecting, i think its something to do with the injection process. 

inject-apk output: Keystore password for signer #1: 
Failed to load signer "signer #1"
java.io.IOException: Keystore was tampered with, or password was incorrect
	at java.base/sun.security.provider.JavaKeyStore.engineLoad(JavaKeyStore.java:792)
	at java.base/sun.security.util.KeyStoreDelegator.engineLoad(KeyStoreDelegator.java:243)
	at java.base/java.security.KeyStore.load(KeyStore.java:1479)
	at com.android.apksigner.SignerParams.loadKeyStoreFromFile(SignerParams.java:353)
	at com.android.apksigner.SignerParams.loadPrivateKeyAndCertsFromKeyStore(SignerParams.java:239)
	at com.android.apksigner.SignerParams.loadPrivateKeyAndCerts(SignerParams.java:181)
	at com.android.apksigner.ApkSignerTool.getSignerConfig(ApkSignerTool.java:368)
	at com.android.apksigner.ApkSignerTool.sign(ApkSignerTool.java:291)
	at com.android.apksigner.ApkSignerTool.main(ApkSignerTool.java:84)
Caused by: java.security.UnrecoverableKeyException: Password verification failed
	at java.base/sun.security.provider.JavaKeyStore.engineLoad(JavaKeyStore.java:790)
	... 8 more
Verifying alignment of /home/rainer/Desktop/test/test.apk (4)...
      60 res/mipmap-xxhdpi/app_icon.png (OK)
    8940 res/mipmap-xxhdpi/ic_launcher_foreground.png (OK)
   31768 res/mipmap-xxhdpi/app_icon_round.png (OK)
   40648 res/mipmap-xxhdpi/ic_launcher_background.png (OK)
[+] Removed /tmp/tmp.SXhZHbAAVk

so i try injecting the unsigned apk and it says its corrupted

https://i.imgur.com/XNjbLGV.png

pls help 👍 
discord: Rainer#0102

(built and injected on linux mint MATE)

**Comment by Masters110** [comment]
Download it again

**Comment by Devilx86** [comment]
Hi, As it says in the output you posted, This is because you entered the wrong key store password.
